dist: trusty
sudo: required

services:
- docker

env:
  global:
  - REPO="danielehc/packer_boxes"

script: |
  if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
    echo cron script
  else
    echo standard build process
  fi

